openapi: 3.0.0
info:
  title: Sriflix API
  description: REST API for Sriflix Web App
  version: 1.0.0

servers:
  - url: http://localhost:8000/api
    description: Local
  - url: https://sriflix.kurniawanc.com/api
    description: Production

paths:
  /movies:
    get:
      summary: Returns all movies.
      responses:
        "200":
          description: Get all movies response
          content:
            application/json:
              schema:
                type: object
                properties:
                  movies:
                    type: array
                    example:
                      [
                        {
                          id: "123abc",
                          title: "movie name",
                          description: "some movie description",
                          video_url: "link to movie video url",
                        },
                        {
                          id: "321bca",
                          title: "movie name",
                          description: "some movie description",
                          video_url: "link to movie video url",
                        },
                        {
                          id: "132acb",
                          title: "movie name",
                          description: "some movie description",
                          video_url: "link to movie video url",
                        },
                      ]
